# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Linmord"
weight = -4

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/notname06138761"
weight = -3

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "qq"
name = "qq"
url = "https://qm.qq.com/q/WwyESfZkMa"
weight = -2

[social.params]
icon = "brand-qq"

[[social]]
identifier = "rss"
name = "Rss"
url = "./index.xml"
weight = -1

[social.params]
icon = "rss"


